# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "react"
    directory: "/"
    schedule:
      interval: "weekly"
 - package-ecosystem: "react"
  directory: "/"
  schedule:
    interval: "weekly"     
   "gatsby": "^5.10.0",
    "gatsby-plugin-google-gtag": "^5.10.0",
    "gatsby-plugin-image": "^3.10.0",
    "gatsby-plugin-mdx": "^5.10.0",
    "gatsby-plugin-netlify-cms": "^7.10.0",
    "gatsby-plugin-sass": "^6.10.0",
    "gatsby-plugin-sharp": "^5.10.0",
    "gatsby-source-filesystem": "^5.10.0",
    "gatsby-transformer-sharp": "^5.10.0",
    "netlify-cms-app": "^2.15.72",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "sass": "^1.63.2"
